name: build_test
on:
  push:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt install -y libgc-dev

      - name: Setup Vlang
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true

      - name: Install dependencies
        run: |
          cd ../ && git clone -b development_process https://github.com/freeflowuniverse/crystallib.git
          cd crystallib && bash install.sh
          cd ../
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build V Client
        run: |
          bash install.sh
          for main in $(ls web3gw/examples/**/*.v); do 
            v $main
          done

      - name: Build Server
        run: |
          cd web3gw/server
          go build
