name: build_test
on:
  push:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt install -y libgc-dev

      - name: Setup Vlang
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true

      - name: Install dependencies
        run: |
          cd ../ && git clone -b development https://github.com/freeflowuniverse/crystallib.git
          cd crystallib && bash install.sh
          cd ../
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build V Client
        run: |
          v scripts/main.v
          v scripts/main_eth.v
          v scripts/main_explorer.v
          v scripts/main_nostr.v
          v scripts/main_tfchain.v
          v scripts/main_tfgrid.v
          v scripts/main_btc.v


      - name: Build Server
        run: |
          cd server
          go build
