name: build_test
on:
  push:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt install -y libgc-dev

      - name: Setup Vlang
        uses: vlang/setup-v@v1.3
        with:
          check-latest: true

      - name: Install dependencies
        run: |
          mkdir -p ~/code/github/freeflowuniverse
          cd ~/code/github/freeflowuniverse
          git clone https://github.com/freeflowuniverse/webcomponents.git
          git clone https://github.com/freeflowuniverse/crystallib.git
          cd crystallib && bash install.sh
          cd ../

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build V Client
        run: |
          bash manual/install.sh

      - name: Build Server
        run: |
          cd web3gw
          go build
